Merge "D:/FastCAE/My_Work_FastCAE_Soft/bin/../temp/geometry.brep";
Geometry.OCCFixDegenerated = 1;
Geometry.OCCFixSmallEdges = 1;
Geometry.OCCFixSmallFaces = 1;
Geometry.OCCSewFaces = 1;
Mesh.Algorithm = 2;
Mesh.Algorithm3D = 2;
Mesh.CharacteristicLengthFactor = 1;
Mesh.CharacteristicLengthMin = 0;
Mesh.CharacteristicLengthMax = 100;
Mesh.ElementOrder = 1;
Mesh.RecombineAll = 0;
Mesh.Smoothing = 20;
Mesh.SubdivisionAlgorithm = 0;
//+
SetFactory("OpenCASCADE");
